/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : common.h
  * @brief          : Global include file, collecting all common headers and defines
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __COMMON_H
#define __COMMON_H

#ifdef __cplusplus
extern "C" {
#endif

/* 1. Standard C Libraries ---------------------------------------------------*/
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

/* 2. Hardware Abstraction Layer (HAL / LL Libraries) ------------------------*/
#include "main.h"      /* Contains hardware definitions generated by CubeMX */
#include "stm32h7xx_hal.h"

/* 3. Peripheral Modules -----------------------------------------------------*/
#include "i2c.h"
#include "usart.h"
#include "gpio.h"

/* 4. User Modules -----------------------------------------------------------*/
#include "UserSmbus.h"


/* 5. Global Macros ----------------------------------------------------------*/
#define UNUSED_VARIABLE(x) (void)(x)
#define ARRAY_SIZE(arr)    (sizeof(arr) / sizeof(arr[0]))

/* 6. Global Typedefs --------------------------------------------------------*/
typedef enum {
    STATUS_OK = 0,
    STATUS_ERROR,
    STATUS_BUSY,
    STATUS_TIMEOUT
} GlobalStatus_t;

#ifdef __cplusplus
}
#endif

#endif /* __COMMON_H */